import html2canvas from 'html2canvas';
import { SpreadResult, ProfitResult } from '../types';

export interface ScreenshotOptions {
  elementId: string;
  width?: number;
  height?: number;
  scale?: number;
}

export interface ScreenshotData {
  tradingPair: string;
  buyExchange: string;
  sellExchange: string;
  buyPrice: number;
  sellPrice: number;
  spreadPercent: number;
  estimatedProfit: number;
  isProfitable: boolean;
  timestamp: Date;
  disclaimer: string;
}

const WATERMARK_TEXT = 'Generated by Arbitrage Scanner - For reference only, not investment advice';

export async function generateScreenshot(
  spread: SpreadResult,
  profit: ProfitResult,
  options?: Partial<ScreenshotOptions>
): Promise<string> {
  const element = document.getElementById(options?.elementId || 'opportunity-content');

  if (!element) {
    throw new Error('Element not found for screenshot');
  }

  const canvas = await html2canvas(element, {
    width: options?.width || 800,
    height: options?.height || 600,
    scale: options?.scale || 2,
    backgroundColor: '#ffffff',
    logging: false,
  });

  return canvas.toDataURL('image/png');
}

export async function generateShareableScreenshot(
  spread: SpreadResult,
  profit: ProfitResult
): Promise<Blob> {
  const dataUrl = await generateScreenshot(spread, profit);
  const response = await fetch(dataUrl);
  return response.blob();
}

export function downloadScreenshot(dataUrl: string, filename: string): void {
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function createShareableText(spread: SpreadResult, profit: ProfitResult): string {
  const lines = [
    `🚨 Arbitrage Opportunity Detected!`,
    ``,
    `📊 ${spread.pair.symbol}`,
    `💰 Buy: ${spread.buyExchange} @ ${spread.buyPrice.toFixed(2)}`,
    `💵 Sell: ${spread.sellExchange} @ ${spread.sellPrice.toFixed(2)}`,
    `📈 Spread: ${spread.spreadPercent.toFixed(2)}%`,
    `💵 Est. Profit: ${profit.netProfit.toFixed(2)} USDT (${profit.isProfitable ? 'Profitable' : 'Unprofitable'})`,
    ``,
    `⚠️ For reference only, not investment advice.`,
    ``,
    `Generated by Arbitrage Scanner`,
  ];

  return lines.join('\n');
}

export function generateShareUrl(
  platform: 'reddit' | 'discord',
  spread: SpreadResult,
  profit: ProfitResult
): string {
  const text = createShareableText(spread, profit);
  const encodedText = encodeURIComponent(text);

  switch (platform) {
    case 'reddit':
      return `https://www.reddit.com/submit?text=${encodedText}`;
    case 'discord':
      return `https://discord.com/channels/@me?message=${encodedText}`;
    default:
      throw new Error(`Unknown platform: ${platform}`);
  }
}

export function generateTwitterShareUrl(spread: SpreadResult, profit: ProfitResult): string {
  const text = `🚨 Arbitrage Opportunity: ${spread.pair.symbol} ${spread.spreadPercent.toFixed(2)}% spread on ${spread.buyExchange} → ${spread.sellExchange}. Est. profit: ${profit.netProfit.toFixed(2)} USDT`;
  return `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
}

export function generateTelegramShareUrl(spread: SpreadResult, profit: ProfitResult): string {
  const text = createShareableText(spread, profit);
  return `https://t.me/share/url?text=${encodeURIComponent(text)}`;
}
